### ISSUE TITLE
Funciones innecesarias

### ISSUE THREAD

**Issue by DanBaDo** [tmayolgomila/lista-tareas-con-fetch#1]
Muchas de estas funciones no se usan. Deberían de eliminarse antes de entregar el código.

Supongo que las conservas a nivel de documentación. Sería mejor guardarlas en otro fichero y ponerle un comentario aclaratorio al principio.

https://github.com/tmayolgomila/lista-tareas-con-fetch/blob/7a47f12bd7336c4544f5ebc95be03c9bf2613281/src/js/component/home.jsx#L37-L150

**Comment by tmayolgomila** [comment]
funciones innecesarias borradas del código
