### ISSUE TITLE
Limpiar antes de entregar

### ISSUE THREAD

**Issue by DanBaDo** [tmayolgomila/lista-tareas-con-fetch#2]
La presentación del código es muy importante. Todos estas lineas comentadas, si no son necesarias, deberían eliminarse.

https://github.com/tmayolgomila/lista-tareas-con-fetch/blob/7a47f12bd7336c4544f5ebc95be03c9bf2613281/src/js/component/home.jsx#L17-L19

**Comment by tmayolgomila** [comment]
arreglado

**Comment by DanBaDo** [comment]
Mucho mejor. :-)
En adelante intenta que no sólo la indentación refleje cómo el código está anidado, sino que las lineas en blanco dividan bloques de código significativos. Las lineas que completan una tarea específica juntas y separadas con una linea en blanco del resto.
