### ISSUE TITLE
Uso adecuado de useEffect

### ISSUE THREAD

**Issue by DanBaDo** [tmayolgomila/lista-tareas-con-fetch#3]
Este `useEffect` quermos que funcione cada vez que se modifica el `state` "`tasks`" para que se actualice la lista de tareas en la API.

https://github.com/tmayolgomila/lista-tareas-con-fetch/blob/7a47f12bd7336c4544f5ebc95be03c9bf2613281/src/js/component/home.jsx#L29-L31

El control sobre cuando se ejecuta un `useEffect` nos lo da el array que recibe (o no) como segundo argumento. El `useEffect` se ejecutará siempre una vez al mostrarse el componente, y otra vez cada vez que se actualice el valor de cualquier `state` o `prop` que esté en el array del segundo argumento del `useEffect`.

Tienes otro `useEffect` anterior al que proporcionas el array: 
https://github.com/tmayolgomila/lista-tareas-con-fetch/blob/7a47f12bd7336c4544f5ebc95be03c9bf2613281/src/js/component/home.jsx#L20-L27

En este caso el array está vacío, con lo que este `useEffect` se ejecutará cada vez que se "cree" el componente en la pantalla y no se ejecutará más mientras no desaparezca de la pantalla y sea creado nuevamente.

En el `useEffect` que mencionamos al principio no proporcionas un array en el segundo argumento. Cuando hacemos esto el código de la función en el primer argumento del `useEffect` se ejecuta como si estuviese en el cuerpo del componente: cada vez que cambia cualquier `state` o `prop`. Por eso cada vez que pulsas una tecla escribiendo una tarea, la aplicación actualiza la lista de tareas en la API a pesar de no haber cambiado, con el consiguiente desperdicio de recursos.

Queremos que se ejecute sólo cuando cambia el `state` "`tasks`", así que como segundo argumento hemos de proporcionar un array que contenga en su interior dicho `state`:

```js
useEffect(
    () => {
       // Tu código aquí...
    },
    [tasks]
)
```

**Comment by tmayolgomila** [comment]
useEffect arreglado
